Repository iota-uz/iota-sdk, pull requests merged in 2025-05, with the labels that each got.

#281 Chat Widget for Website & CRM module integration #259
  .golangci.yml
  CLAUDE.md
  migrations/changes-1745997548.sql
  modules/core/domain/value_objects/phone/phone.go
  modules/crm/domain/aggregates/chat/chat.go
  modules/crm/domain/aggregates/chat/chat_events.go
  modules/crm/domain/aggregates/chat/chat_implementation.go
  modules/crm/domain/aggregates/chat/chat_repository.go
  modules/crm/domain/aggregates/client/client.go
  modules/crm/domain/aggregates/client/client_repository.go
  modules/crm/handlers/client_handler.go
  modules/crm/handlers/sms_handler.go
  modules/crm/infrastructure/cpass-providers/twilio.go
  modules/crm/infrastructure/persistence/chat_repository.go
  modules/crm/infrastructure/persistence/chat_repository_test.go
  modules/crm/infrastructure/persistence/client_repository.go
  modules/crm/infrastructure/persistence/client_repository_test.go
  modules/crm/infrastructure/persistence/crm_mappers.go
  modules/crm/infrastructure/persistence/crm_mappers_test.go
  modules/crm/infrastructure/persistence/models/models.go
  modules/crm/infrastructure/persistence/schema/crm-schema.sql
  modules/crm/module.go
  modules/crm/presentation/controllers/chat_controller.go
  modules/crm/presentation/controllers/dtos/client_dto.go
  modules/crm/presentation/controllers/twilio_controller.go
  modules/crm/presentation/mappers/mappers.go
  modules/crm/presentation/viewmodels/chat_viewmodel.go
  modules/crm/services/chat_service.go
  modules/crm/services/client_service.go
  modules/website/presentation/assets/js/aichat.js
  modules/website/presentation/controllers/ai_chat_controller.go
  modules/website/presentation/controllers/aichat_controller.go
  modules/website/presentation/controllers/dtos/aichat_dto.go
  modules/website/presentation/templates/pages/aichat/aichat.templ
  modules/website/presentation/templates/pages/aichat/aichat_templ.go
  modules/website/presentation/templates/pages/aichat/test_wc.templ
  modules/website/presentation/templates/pages/aichat/test_wc_templ.go
  modules/website/services/setup_test.go
  modules/website/services/website_chat_service.go
  modules/website/services/website_chat_service_test.go
  pkg/composables/sidebar.go
  pkg/testutils/utils.go
Labels: draft

#284 feat: unified billing #283
  .env.example
  Makefile
  docs/CONTRIBUTING.MD
  go.mod
  go.sum
  migrations/changes-1747574914.sql
  modules/billing/domain/aggregates/billing/billing.go
  modules/billing/domain/aggregates/billing/billing_events.go
  modules/billing/domain/aggregates/billing/billing_impl.go
  modules/billing/domain/aggregates/billing/billing_provider.go
  modules/billing/domain/aggregates/billing/billing_repository.go
  modules/billing/domain/aggregates/details/click_details_impl.go
  modules/billing/domain/aggregates/details/details.go
  modules/billing/domain/aggregates/details/octo_details_impl.go
  modules/billing/domain/aggregates/details/payme_details_impl.go
  modules/billing/domain/aggregates/details/stripe_details_impl.go
  modules/billing/infrastructure/persistence/billing_mappers.go
  modules/billing/infrastructure/persistence/billing_mappers_test.go
  modules/billing/infrastructure/persistence/billing_repository.go
  modules/billing/infrastructure/persistence/billing_repository_test.go
  modules/billing/infrastructure/persistence/models/models.go
  modules/billing/infrastructure/persistence/schema/billing-schema.sql
  modules/billing/infrastructure/persistence/setup_test.go
  modules/billing/infrastructure/providers/click_provider.go
  modules/billing/infrastructure/providers/payme_provider.go
  modules/billing/module.go
  modules/billing/permissions/constants.go
  modules/billing/presentation/controllers/click_controller.go
  modules/billing/presentation/controllers/payme_controller.go
  modules/billing/presentation/locales/en.json
  modules/billing/presentation/locales/ru.json
  modules/billing/presentation/locales/uz.json
  modules/billing/services/billing_service.go
  modules/billing/services/billing_service_test.go
  modules/billing/services/setup_test.go
  modules/load.go
  pkg/configuration/environment.go
  pkg/middleware/logging.go
Labels: enhancement

#267 Runtime CRUD builder
  components/base/input/input.templ
  components/base/input/input_templ.go
  components/scaffold/form/builders.go
  components/scaffold/form/fields.go
  components/scaffold/form/form.templ
  components/scaffold/form/form_templ.go
  components/scaffold/form/types.go
  components/scaffold/table/drawers.templ
  components/scaffold/table/drawers_templ.go
  components/scaffold/table/helpers.go
  components/scaffold/table/table.templ
  components/scaffold/table/table_templ.go
  modules/core/presentation/controllers/di_example.go
  pkg/crud/errors.go
  pkg/crud/factory.go
  pkg/crud/handlers.go
  pkg/crud/options.go
  pkg/crud/patcher.go
  pkg/crud/schema.go
  pkg/crud/schema_test.go
  pkg/crud/service.go
  pkg/crud/store.go
  pkg/crud/types.go
  pkg/crud/utils.go
Labels: enhancement, help wanted
